version: "3"
name: "shopping-cart"
services:
  postgres:
    container_name: shopping-cart-postgres
    hostname: shopping-cart-postgres
    build:
      context: ./db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db/data/.postgres/:/var/lib/postgresql/data
  backend:
    container_name: shopping-cart-backend
    hostname: shopping-cart-backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    deploy:
      mode: replicated
      replicas: 1
networks:
  default:
    name: shopping-cart
    driver: bridge
