version: "3"
name: "shopping-cart"
services:
  postgres:
    build:
      context: ./db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db/data/postgres/:/var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    deploy:
      mode: replicated
      replicas: 1
